In [2]:
import pandas as pd
import sys
import sqlite3
import numpy as np
!pip install sklearn --upgrade
!pip install joblib

Requirement already up-to-date: sklearn in c:\users\bocli\anaconda3\lib\site-packages (0.0)
Requirement already satisfied, skipping upgrade: scikit-learn in c:\users\bocli\anaconda3\lib\site-packages (from sklearn) (0.21.3)
Requirement already satisfied, skipping upgrade: numpy>=1.11.0 in c:\users\bocli\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.16.5)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in c:\users\bocli\anaconda3\lib\site-packages (from scikit-learn->sklearn) (0.13.2)
Requirement already satisfied, skipping upgrade: scipy>=0.17.0 in c:\users\bocli\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.4.1)
Requirement already satisfied: joblib in c:\users\bocli\anaconda3\lib\site-packages (0.13.2)

In [4]:
#importing data 
# Read sqlite query results into a pandas DataFrame
con = sqlite3.connect("data/Casino.sqlite")
c = con.cursor()

In [5]:
c.execute("SELECT * FROM casinoSW limit 5;")
results= c.fetchall()
print(results)
# for row in c.execute("SELECT * FROM casinoSW"):
#     print(row)

[(0, 2014, 'Arizona', 'Coconino County', ' Tribal Authorized Casino', 'Alters or Cancels Transaction to Avoid CTR Requirement', 1, 35.829692, -111.773728), (1, 2014, 'Arizona', 'Coconino County', ' Tribal Authorized Casino', 'Exchanges Small Bills for Large Bills or Vice Versa', 1, 35.829692, -111.773728), (2, 2014, 'Arizona', 'Coconino County', ' Tribal Authorized Casino', 'Other Structuring', 1, 35.829692, -111.773728), (3, 2014, 'Arizona', 'Coconino County', ' Tribal Authorized Casino', 'Provided Questionable or False Documentation', 1, 35.829692, -111.773728), (4, 2016, 'Arizona', 'Coconino County', ' Tribal Authorized Casino', 'Account Takeover', 1, 35.829692, -111.773728)]

In [4]:
#column names
names = [description[0] for description in c.description]
names

['id',
 'Year',
 'State',
 'Countym',
 'Industry',
 'Suspicious Activity',
 'Count',
 'Lat',
 'Long']

In [5]:
# def converter(x):
#     if x==' Tribal Authorized Casino':
#         return 0
#     elif x==' Card Club':
#         return 1
#     elif x==' State Licensed Casino':
#         return 2
#     else:
#         return 3
df = pd.read_sql_query("SELECT * FROM casinoSW",  con)
df

,id,Year,State,Countym,Industry,Suspicious Activity,Count,Lat,Long
0,0,2014,Arizona,Coconino County,Tribal Authorized Casino,Alters or Cancels Transaction to Avoid CTR Req...,1,35.829692,-111.773728
1,1,2014,Arizona,Coconino County,Tribal Authorized Casino,Exchanges Small Bills for Large Bills or Vice ...,1,35.829692,-111.773728
2,2,2014,Arizona,Coconino County,Tribal Authorized Casino,Other Structuring,1,35.829692,-111.773728
3,3,2014,Arizona,Coconino County,Tribal Authorized Casino,Provided Questionable or False Documentation,1,35.829692,-111.773728
4,4,2016,Arizona,Coconino County,Tribal Authorized Casino,Account Takeover,1,35.829692,-111.773728
...,...,...,...,...,...,...,...,...,...
7227,7227,2019,Utah,Summit County,Tribal Authorized Casino,Suspicious use of multiple transaction locations,1,40.872060,-110.968486
7228,7228,2019,Utah,Summit County,Tribal Authorized Casino,Transaction Out of Pattern for Customer(s),1,40.872060,-110.968486
7229,7229,2019,Utah,Summit County,Tribal Authorized Casino,Transaction(s) Below BSA Recordkeeping Threshold,3,40.872060,-110.968486
7230,7230,2019,Utah,Summit County,Tribal Authorized Casino,Transaction(s) Below CTR Threshold,1,40.872060,-110.968486
7231,7231,2019,Utah,Summit County,Tribal Authorized Casino,Two or More Individuals Working Together,2,40.872060,-110.968486

In [6]:
test_df = pd.read_sql_query("SELECT * FROM casinoSW",  con).dropna()
test_df

,id,Year,State,Countym,Industry,Suspicious Activity,Count,Lat,Long
0,0,2014,Arizona,Coconino County,Tribal Authorized Casino,Alters or Cancels Transaction to Avoid CTR Req...,1,35.829692,-111.773728
1,1,2014,Arizona,Coconino County,Tribal Authorized Casino,Exchanges Small Bills for Large Bills or Vice ...,1,35.829692,-111.773728
2,2,2014,Arizona,Coconino County,Tribal Authorized Casino,Other Structuring,1,35.829692,-111.773728
3,3,2014,Arizona,Coconino County,Tribal Authorized Casino,Provided Questionable or False Documentation,1,35.829692,-111.773728
4,4,2016,Arizona,Coconino County,Tribal Authorized Casino,Account Takeover,1,35.829692,-111.773728
...,...,...,...,...,...,...,...,...,...
7227,7227,2019,Utah,Summit County,Tribal Authorized Casino,Suspicious use of multiple transaction locations,1,40.872060,-110.968486
7228,7228,2019,Utah,Summit County,Tribal Authorized Casino,Transaction Out of Pattern for Customer(s),1,40.872060,-110.968486
7229,7229,2019,Utah,Summit County,Tribal Authorized Casino,Transaction(s) Below BSA Recordkeeping Threshold,3,40.872060,-110.968486
7230,7230,2019,Utah,Summit County,Tribal Authorized Casino,Transaction(s) Below CTR Threshold,1,40.872060,-110.968486
7231,7231,2019,Utah,Summit County,Tribal Authorized Casino,Two or More Individuals Working Together,2,40.872060,-110.968486

In [7]:
test_df["Industry"].value_counts()

 Tribal Authorized Casino    4478
 State Licensed Casino       1520
 Card Club                   1170
 Other Casino/Card Club        63
Name: Industry, dtype: int64

In [8]:
test_df["Countym"].value_counts()

San Diego County          424
Clark County              404
Los Angeles County        273
Riverside County          264
Contra Costa County       250
                         ...
Marin County                2
Rio Blanco County           2
San Luis Obispo County      2
Sierra County               1
Storey County               1
Name: Countym, Length: 108, dtype: int64

In [9]:
cleanup_industry = {"Industry": {' Tribal Authorized Casino': 0, ' Card Club':1,
                                 ' State Licensed Casino': 2, ' Other Casino/Card Club': 3}}

In [10]:
test_df.replace(cleanup_industry, inplace=True)

In [11]:
test_df["Industry"].value_counts()

0    4478
2    1520
1    1170
3      63
Name: Industry, dtype: int64

In [12]:
test_df

,id,Year,State,Countym,Industry,Suspicious Activity,Count,Lat,Long
0,0,2014,Arizona,Coconino County,0,Alters or Cancels Transaction to Avoid CTR Req...,1,35.829692,-111.773728
1,1,2014,Arizona,Coconino County,0,Exchanges Small Bills for Large Bills or Vice ...,1,35.829692,-111.773728
2,2,2014,Arizona,Coconino County,0,Other Structuring,1,35.829692,-111.773728
3,3,2014,Arizona,Coconino County,0,Provided Questionable or False Documentation,1,35.829692,-111.773728
4,4,2016,Arizona,Coconino County,0,Account Takeover,1,35.829692,-111.773728
...,...,...,...,...,...,...,...,...,...
7227,7227,2019,Utah,Summit County,0,Suspicious use of multiple transaction locations,1,40.872060,-110.968486
7228,7228,2019,Utah,Summit County,0,Transaction Out of Pattern for Customer(s),1,40.872060,-110.968486
7229,7229,2019,Utah,Summit County,0,Transaction(s) Below BSA Recordkeeping Threshold,3,40.872060,-110.968486
7230,7230,2019,Utah,Summit County,0,Transaction(s) Below CTR Threshold,1,40.872060,-110.968486
7231,7231,2019,Utah,Summit County,0,Two or More Individuals Working Together,2,40.872060,-110.968486

In [133]:
new_test_df = test_df.drop(columns=["Countym", "State", "Suspicious Activity", "id", "Lat", "Long"])

new_test_df["Count"] = pd.to_numeric(df["Count"], errors='coerce').fillna(0)

new_test_df

      Year  Industry  Count
0     2014         0    1.0
1     2014         0    1.0
2     2014         0    1.0
3     2014         0    1.0
4     2016         0    1.0
...    ...       ...    ...
7227  2019         0    1.0
7228  2019         0    1.0
7229  2019         0    3.0
7230  2019         0    1.0
7231  2019         0    2.0

[7231 rows x 3 columns]

In [83]:
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import MinMaxScaler,StandardScaler, Normalizer
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.feature_selection import SelectKBest,f_classif
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.metrics import classification_report as report
from random import randint
from sys import maxsize
import warnings
from sklearn.exceptions import DataConversionWarning,UndefinedMetricWarning
warnings.filterwarnings(action='ignore',category=DataConversionWarning)
warnings.filterwarnings(action='ignore',category=UndefinedMetricWarning)

#pipeline: 1) scales model 2) reduces dimensionality 3) tests the model

#this function takes an arugent n_features representing the total number of features to keep
#by iterating through n_features=1 to n_features = max_features we will determine the best set of features
"""
    SUMMARY:  Creates a pipeline with the given data preprocessors and model and then tests the model using the pipeline
    
    
    
    IN: n_features = denotes the number of features, n_features, to select from the overall data set
                        there is a total of 40 columns in the input data and we may not want all of that data
                        some of the featuress could be 'noise' and not be useful to predicting the output.
                        We will use Principal Component Analysis, by way of the SelectKBest function and the f_classif function
                        do decide which selection of features is optimal
        
        testmodel = denotes the model we wish to test in this test run.  could be any classification model that supports
                        the functions "fit" and "fit_transform"
                        

            
    OUT:  Returns the overall model precision

"""

def RunTest(n_features,testmodel):
    X= new_test_df.drop(columns=["Industry"],inplace=False)
    y= new_test_df["Industry"].values.reshape(-1,1) # same as  y = [ df["koi_disposition"].values ]
    X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=randint(0,2**32 - 1))
    #testscaler=MinMaxScaler(feature_range=(-1,1),copy=True)
    testscaler=StandardScaler()
    normalizer=Normalizer()
    testpca=SelectKBest(f_classif,k="all")
    mypipeline=Pipeline([('featurescale',testscaler),("mynormalizer",normalizer), ("anova",testpca), ("model",testmodel)])    
    mypipeline.fit(X_train,y_train)
    predictions=mypipeline.predict(X_test)
    return report(y_test,predictions,output_dict=True)
    



precisions={}
models={KNN(n_neighbors=1):"knn",RandomForestClassifier():"rff",SVC():"svc", LogisticRegression():"lin",
       } #chooses all models from dict list beforehand
for model,name in models.items():
    for n_features in range(3,1,-1): #loops through each model and every step of the way it throws out the worst column
        score=RunTest(n_features,model)["weighted avg"]['precision']
        n=n_features
        precisions[float(score)]=(name,n)
answer=max(precisions)
print(answer,str(precisions.get(answer)))

C:\Users\bocli\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\bocli\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\bocli\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

0.5255496672840776 ('svc', 3)

C:\Users\bocli\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\bocli\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\bocli\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\bocli\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

In [7]:
new_df = pd.read_sql_query("SELECT * FROM casinoSW",  con)
new_df.dropna()

,id,Year,State,Countym,Industry,Suspicious Activity,Count,Lat,Long
0,0,2014,Arizona,Coconino County,Tribal Authorized Casino,Alters or Cancels Transaction to Avoid CTR Req...,1,35.829692,-111.773728
1,1,2014,Arizona,Coconino County,Tribal Authorized Casino,Exchanges Small Bills for Large Bills or Vice ...,1,35.829692,-111.773728
2,2,2014,Arizona,Coconino County,Tribal Authorized Casino,Other Structuring,1,35.829692,-111.773728
3,3,2014,Arizona,Coconino County,Tribal Authorized Casino,Provided Questionable or False Documentation,1,35.829692,-111.773728
4,4,2016,Arizona,Coconino County,Tribal Authorized Casino,Account Takeover,1,35.829692,-111.773728
...,...,...,...,...,...,...,...,...,...
7227,7227,2019,Utah,Summit County,Tribal Authorized Casino,Suspicious use of multiple transaction locations,1,40.872060,-110.968486
7228,7228,2019,Utah,Summit County,Tribal Authorized Casino,Transaction Out of Pattern for Customer(s),1,40.872060,-110.968486
7229,7229,2019,Utah,Summit County,Tribal Authorized Casino,Transaction(s) Below BSA Recordkeeping Threshold,3,40.872060,-110.968486
7230,7230,2019,Utah,Summit County,Tribal Authorized Casino,Transaction(s) Below CTR Threshold,1,40.872060,-110.968486
7231,7231,2019,Utah,Summit County,Tribal Authorized Casino,Two or More Individuals Working Together,2,40.872060,-110.968486

In [8]:
cat_industry = {"Industry": {' Tribal Authorized Casino': 0, ' Card Club':1,
                                 ' State Licensed Casino': 2, ' Other Casino/Card Club': 3}}

In [24]:
new_df.replace(cat_industry, inplace=True)

In [25]:
new_df

,id,Year,State,Countym,Industry,Suspicious Activity,Count,Lat,Long
0,0,2014,Arizona,Coconino County,0.0,Alters or Cancels Transaction to Avoid CTR Req...,1,35.829692,-111.773728
1,1,2014,Arizona,Coconino County,0.0,Exchanges Small Bills for Large Bills or Vice ...,1,35.829692,-111.773728
2,2,2014,Arizona,Coconino County,0.0,Other Structuring,1,35.829692,-111.773728
3,3,2014,Arizona,Coconino County,0.0,Provided Questionable or False Documentation,1,35.829692,-111.773728
4,4,2016,Arizona,Coconino County,0.0,Account Takeover,1,35.829692,-111.773728
...,...,...,...,...,...,...,...,...,...
7227,7227,2019,Utah,Summit County,0.0,Suspicious use of multiple transaction locations,1,40.872060,-110.968486
7228,7228,2019,Utah,Summit County,0.0,Transaction Out of Pattern for Customer(s),1,40.872060,-110.968486
7229,7229,2019,Utah,Summit County,0.0,Transaction(s) Below BSA Recordkeeping Threshold,3,40.872060,-110.968486
7230,7230,2019,Utah,Summit County,0.0,Transaction(s) Below CTR Threshold,1,40.872060,-110.968486
7231,7231,2019,Utah,Summit County,0.0,Two or More Individuals Working Together,2,40.872060,-110.968486

In [26]:
cat_county = pd.get_dummies(new_df[{"Countym","Suspicious Activity","State"}])
new_cat_county=cat_county.reset_index(level=0)

In [27]:
new_cat_county = new_cat_county.rename(columns={"index":"id"})

In [28]:
all_cat = new_df.merge(new_cat_county, left_on="id", right_on="id")
all_cat

,id,Year,State,Countym,Industry,Suspicious Activity,Count,Lat,Long,Suspicious Activity_ACH,...,Countym_Yavapai County,Countym_Yolo County,Countym_Yuba County,Countym_Yuma County,State_Arizona,State_California,State_Colorado,State_Nevada,State_New Mexico,State_Utah
0,0,2014,Arizona,Coconino County,0.0,Alters or Cancels Transaction to Avoid CTR Req...,1,35.829692,-111.773728,0,...,0,0,0,0,1,0,0,0,0,0
1,1,2014,Arizona,Coconino County,0.0,Exchanges Small Bills for Large Bills or Vice ...,1,35.829692,-111.773728,0,...,0,0,0,0,1,0,0,0,0,0
2,2,2014,Arizona,Coconino County,0.0,Other Structuring,1,35.829692,-111.773728,0,...,0,0,0,0,1,0,0,0,0,0
3,3,2014,Arizona,Coconino County,0.0,Provided Questionable or False Documentation,1,35.829692,-111.773728,0,...,0,0,0,0,1,0,0,0,0,0
4,4,2016,Arizona,Coconino County,0.0,Account Takeover,1,35.829692,-111.773728,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7227,7227,2019,Utah,Summit County,0.0,Suspicious use of multiple transaction locations,1,40.872060,-110.968486,0,...,0,0,0,0,0,0,0,0,0,1
7228,7228,2019,Utah,Summit County,0.0,Transaction Out of Pattern for Customer(s),1,40.872060,-110.968486,0,...,0,0,0,0,0,0,0,0,0,1
7229,7229,2019,Utah,Summit County,0.0,Transaction(s) Below BSA Recordkeeping Threshold,3,40.872060,-110.968486,0,...,0,0,0,0,0,0,0,0,0,1
7230,7230,2019,Utah,Summit County,0.0,Transaction(s) Below CTR Threshold,1,40.872060,-110.968486,0,...,0,0,0,0,0,0,0,0,0,1
7231,7231,2019,Utah,Summit County,0.0,Two or More Individuals Working Together,2,40.872060,-110.968486,0,...,0,0,0,0,0,0,0,0,0,1

In [32]:
the_df=all_cat.drop(columns={"State", "Countym", "Suspicious Activity", "Lat", "Long"})

In [33]:
the_df

,id,Year,Industry,Count,Suspicious Activity_ACH,Suspicious Activity_Account Takeover,Suspicious Activity_Against Financial Institution Customer(s),Suspicious Activity_Against Financial Institution(s),Suspicious Activity_Alters or Cancels Transaction to Avoid BSA Recordkeeping Requirement,Suspicious Activity_Alters or Cancels Transaction to Avoid CTR Requirement,...,Countym_Yavapai County,Countym_Yolo County,Countym_Yuba County,Countym_Yuma County,State_Arizona,State_California,State_Colorado,State_Nevada,State_New Mexico,State_Utah
0,0,2014,0.0,1,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
1,1,2014,0.0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,2,2014,0.0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,3,2014,0.0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,4,2016,0.0,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7227,7227,2019,0.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7228,7228,2019,0.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7229,7229,2019,0.0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7230,7230,2019,0.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7231,7231,2019,0.0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [47]:
# Replacing Count column's strings and "," with int dtypes
the_df["Count"]=pd.Series(the_df["Count"].astype(str))
the_df["Count"] = the_df["Count"].apply(lambda x: float(x.split()[0].replace(',', '')))
the_df["Count"].astype(int)

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [49]:
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import MinMaxScaler,StandardScaler, Normalizer
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.feature_selection import SelectKBest,f_classif
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.metrics import classification_report as report
from random import randint
from sys import maxsize
import warnings
from sklearn.exceptions import DataConversionWarning,UndefinedMetricWarning
warnings.filterwarnings(action='ignore',category=DataConversionWarning)
warnings.filterwarnings(action='ignore',category=UndefinedMetricWarning)

#pipeline: 1) scales model 2) reduces dimensionality 3) tests the model

#this function takes an arugent n_features representing the total number of features to keep
#by iterating through n_features=1 to n_features = max_features we will determine the best set of features
"""
    SUMMARY:  Creates a pipeline with the given data preprocessors and model and then tests the model using the pipeline
    
    
    
    IN: n_features = denotes the number of features, n_features, to select from the overall data set
                        there is a total of 40 columns in the input data and we may not want all of that data
                        some of the featuress could be 'noise' and not be useful to predicting the output.
                        We will use Principal Component Analysis, by way of the SelectKBest function and the f_classif function
                        do decide which selection of features is optimal
        
        testmodel = denotes the model we wish to test in this test run.  could be any classification model that supports
                        the functions "fit" and "fit_transform"
                        

            
    OUT:  Returns the overall model precision

"""

def RunTest(n_features,testmodel):
    X= the_df.drop(columns=["Industry"],inplace=False)
    y= the_df["Industry"].values.reshape(-1,1) # same as  y = [ df["koi_disposition"].values ]
    X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=randint(0,2**32 - 1))
    #testscaler=MinMaxScaler(feature_range=(-1,1),copy=True)
    testscaler=StandardScaler()
    normalizer=Normalizer()
    testpca=SelectKBest(f_classif,k="all")
    mypipeline=Pipeline([('featurescale',testscaler),("mynormalizer",normalizer), ("anova",testpca), ("model",testmodel)])    
    mypipeline.fit(X_train,y_train)
    predictions=mypipeline.predict(X_test)
    return report(y_test,predictions,output_dict=True)
    



precisions={}
models={KNN(n_neighbors=202):"knn",RandomForestClassifier():"rff",SVC():"svc"} #chooses all models from dict list beforehand
for model,name in models.items():
    for n_features in range(3,1,-1): #loops through each model and every step of the way it throws out the worst column
        score=RunTest(n_features,model)["weighted avg"]['precision']
        n=n_features
        precisions[float(score)]=(name,n)
answer=max(precisions)
print(answer,str(precisions.get(answer)))

C:\Users\bocli\Anaconda3\lib\site-packages\sklearn\utils\extmath.py:747: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\bocli\Anaconda3\lib\site-packages\sklearn\utils\extmath.py:688: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').